import { type NextPage } from "next";
import Head from "next/head";
import { Button } from "~/components/ui/button";
import { api } from "~/utils/api";
import { faker } from "@faker-js/faker";
import Carucel from "~/components/carucel";

const Home: NextPage = () => {
    const utils = api.useContext();

    const { data } = api.product.getAll.useQuery();

    const { mutate } = api.product.addProduct.useMutation({
        onSuccess() {
            void utils.product.getAll.invalidate();
        },
    });

    const handleAdd = () => {
        mutate({
            categoryName: faker.commerce.department(),
            image: "",
            name: faker.commerce.product(),
            price: Number(faker.commerce.price({ min: 100, max: 10000 })),
            categoryId: "",
        });
    };

    return (
        <>
            <Head>
                <title>WebStore</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex h-full flex-1">
                <div className="container border-x bg-background p-0 pt-8 lg:p-4">
                    <Carucel data={data || []} title="Products" />
                </div>
            </main>
        </>
    );
};

export default Home;
