import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { headers } from "next/headers";

import { cn } from "~/lib/utils";
import { TRPCReactProvider } from "~/trpc/react";
import Header from "./_components/navigations/header";
import { ThemeProvider } from "./_components/theme-provider";
import { Toaster } from "./_components/ui/toaster";
import JotaiProvider from "./jotai-provider";
const inter = Inter({
    subsets: ["latin"],
});

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={(cn(inter.className), "flex h-screen flex-col")}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <TRPCReactProvider headers={headers()}>
                        <JotaiProvider>
                            <Header />
                            {children}
                            <Toaster />
                        </JotaiProvider>
                    </TRPCReactProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
